app.listen(process.env.PORT);
var schedule = require('node-schedule');
const Discord = require("discord.js");
const bot = new Discord.Client();
const fs = require("fs");
const active = new Map();
bot.commands = new Discord.Collection();
bot.aliases = new Discord.Collection();
["aliases", "commands"].forEach(x => bot[x] = new Discord.Collection());
["command", "event", "reaction"].forEach(x => require(`./handlers/${x}`)(bot));
bot.login(process.env.token);
